---
#https://github.com/kewlfft/ansible-aur
# ai_generated: https://chatgpt.com/share/672581b8-9579-4fec-82a8-0b0a4fe3f322

- name: Ensure yay is installed (if it's not already)
  community.general.pacman:
    name: yay
    state: present
    update_cache: true
  become: true

- name: Install JetBrains CLion from AUR using yay
  ansible.builtin.command: yay -S --noconfirm clion
  args:
    creates: /usr/bin/clion

# - name: Install CLion with AUR
#   kewlfft.aur.aur:
#     name: clion
#     use: makepkg
#     state: present
#   become: yes
#   become_user: ansible_env.USER

- name: Verify JetBrains CLion installation
  command: clion --version
  register: clion_version
  ignore_errors: yes
  become: true

- name: Display CLion version
  debug:
    msg: "{{ clion_version.stdout }}"
